# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1456305804);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1456305924);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1456305444);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1456305684);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1456305564);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1456306044);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 1);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 30);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.rights.3.shown", true);
user_pref("browser.search.countryCode", "CN");
user_pref("browser.search.region", "CN");
user_pref("browser.sessionstore.resume_session_once", true);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20150918100231");
user_pref("browser.slowStartup.averageTime", 10149);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20150918100231");
user_pref("browser.startup.homepage_override.mstone", "41.0");
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("datareporting.healthreport.lastDataSubmissionRequestedTime", "1456305389646");
user_pref("datareporting.healthreport.lastDataSubmissionSuccessfulTime", "1456305391104");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1456391791104");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1443683642560");
user_pref("datareporting.policy.firstRunTime", "1443626415118");
user_pref("datareporting.sessions.current.activeTicks", 16);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 7357);
user_pref("datareporting.sessions.current.main", 697);
user_pref("datareporting.sessions.current.sessionRestored", 6522);
user_pref("datareporting.sessions.current.startTime", "1456305321556");
user_pref("datareporting.sessions.current.totalTime", 824);
user_pref("datareporting.sessions.currentIndex", 3);
user_pref("datareporting.sessions.prunedIndex", 2);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 3);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{\"langpack-en-GB@firefox.mozilla.org\":{\"version\":\"41.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false},\"langpack-en-ZA@firefox.mozilla.org\":{\"version\":\"41.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false},\"langpack-zh-CN@firefox.mozilla.org\":{\"version\":\"41.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-zh-CN@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false}}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.enabledAddons", "ubufox%40ubuntu.com:3.2,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:41.0");
user_pref("extensions.getAddons.cache.lastUpdate", 1456305806);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.hotfix.lastVersion", "20160128.01");
user_pref("extensions.lastAppVersion", "41.0");
user_pref("extensions.lastPlatformVersion", "41.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.xpiState", "{\"app-global\":{\"langpack-en-GB@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"e\":false,\"v\":\"40.0.3\",\"st\":1442573952000},\"langpack-en-ZA@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"e\":false,\"v\":\"40.0.3\",\"st\":1442573952000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"37.0\",\"st\":1443684013000,\"mt\":1442573084000},\"langpack-zh-CN@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-zh-CN@firefox.mozilla.org.xpi\",\"e\":false,\"v\":\"40.0.3\",\"st\":1442574038000}},\"app-system-share\":{\"ubufox@ubuntu.com\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com.xpi\",\"e\":true,\"v\":\"3.0\",\"st\":1442597167000}}}");
user_pref("gecko.buildID", "20150918100231");
user_pref("gecko.mstone", "41.0");
user_pref("idle.lastDailyNotification", 1456305513);
user_pref("media.gmp-gmpopenh264.lastUpdate", 1456305390);
user_pref("media.gmp-gmpopenh264.version", "1.5.3");
user_pref("media.gmp-manager.buildID", "20150918100231");
user_pref("media.gmp-manager.lastCheck", 1456305389);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.http.altsvc.enabled", false);
user_pref("network.http.altsvc.oe", false);
user_pref("network.http.atsvc.enabled", false);
user_pref("network.http.atsvc.oe", false);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1456305513);
user_pref("places.history.expiration.transient_current_max_pages", 12822);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateClearSavedPwdsOnExit", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1456305513);
user_pref("toolkit.startup.last_success", 1456305322);
user_pref("toolkit.telemetry.cachedClientID", "16b4cc14-8636-459c-b815-978fbfcb407e");
user_pref("toolkit.telemetry.previousBuildID", "20150328222441");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
