# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1456308394);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1456308514);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1456320142);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1456308198);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1456308078);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1456308634);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 4);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 30);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.reader.detectedFirstArticle", true);
user_pref("browser.search.countryCode", "CN");
user_pref("browser.search.region", "CN");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20150918100231");
user_pref("browser.slowStartup.averageTime", 3067);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20150918100231");
user_pref("browser.startup.homepage_override.mstone", "41.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":4}");
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1456392550802");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1456307274446");
user_pref("datareporting.policy.firstRunTime", "1456306150801");
user_pref("datareporting.sessions.current.activeTicks", 6);
user_pref("datareporting.sessions.current.firstPaint", 3024);
user_pref("datareporting.sessions.current.main", 169);
user_pref("datareporting.sessions.current.sessionRestored", 3977);
user_pref("datareporting.sessions.current.startTime", "1456325074490");
user_pref("datareporting.sessions.current.totalTime", 28);
user_pref("datareporting.sessions.currentIndex", 12);
user_pref("datareporting.sessions.previous.0", "{\"s\":1456306145726,\"a\":3,\"t\":16,\"c\":true,\"m\":159,\"fp\":877,\"sr\":7058}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1456307259959,\"a\":25,\"t\":156,\"c\":true,\"m\":237,\"fp\":4846,\"sr\":4502}");
user_pref("datareporting.sessions.previous.10", "{\"s\":1456323770613,\"a\":3,\"t\":18,\"c\":true,\"m\":160,\"fp\":2529,\"sr\":2579}");
user_pref("datareporting.sessions.previous.11", "{\"s\":1456324267672,\"a\":5,\"t\":108,\"c\":true,\"m\":128,\"fp\":3688,\"sr\":3736}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1456307957191,\"a\":10,\"t\":291,\"c\":true,\"m\":145,\"fp\":2502,\"sr\":3107}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1456308273235,\"a\":22,\"t\":1578,\"c\":true,\"m\":124,\"fp\":3614,\"sr\":3022}");
user_pref("datareporting.sessions.previous.4", "{\"s\":1456316403960,\"a\":56,\"t\":4859,\"c\":true,\"m\":3708,\"fp\":30159,\"sr\":35932}");
user_pref("datareporting.sessions.previous.5", "{\"s\":1456321826774,\"a\":2,\"t\":10,\"c\":true,\"m\":408,\"fp\":3978,\"sr\":4120}");
user_pref("datareporting.sessions.previous.6", "{\"s\":1456321905611,\"a\":6,\"t\":32,\"c\":true,\"m\":187,\"fp\":5200,\"sr\":5272}");
user_pref("datareporting.sessions.previous.7", "{\"s\":1456321940009,\"a\":19,\"t\":157,\"c\":true,\"m\":294,\"fp\":3933,\"sr\":3982}");
user_pref("datareporting.sessions.previous.8", "{\"s\":1456323515347,\"a\":7,\"t\":37,\"c\":true,\"m\":446,\"fp\":6974,\"sr\":7539}");
user_pref("datareporting.sessions.previous.9", "{\"s\":1456323578393,\"a\":7,\"t\":188,\"c\":true,\"m\":234,\"fp\":3878,\"sr\":3936}");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{\"langpack-en-GB@firefox.mozilla.org\":{\"version\":\"41.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false},\"langpack-en-ZA@firefox.mozilla.org\":{\"version\":\"41.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false},\"langpack-zh-CN@firefox.mozilla.org\":{\"version\":\"41.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-zh-CN@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false}}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.enabledAddons", "ubufox%40ubuntu.com:3.2,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:41.0");
user_pref("extensions.getAddons.cache.lastUpdate", 1456308396);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.hotfix.lastVersion", "20160128.01");
user_pref("extensions.lastAppVersion", "41.0");
user_pref("extensions.lastPlatformVersion", "41.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.xpiState", "{\"app-global\":{\"langpack-en-GB@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"41.0\",\"st\":1442573952000},\"langpack-en-ZA@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"41.0\",\"st\":1442573952000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"41.0\",\"st\":1443684013000,\"mt\":1442573084000},\"langpack-zh-CN@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-zh-CN@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"41.0\",\"st\":1442574038000}},\"app-system-share\":{\"ubufox@ubuntu.com\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com.xpi\",\"e\":true,\"v\":\"3.2\",\"st\":1442597167000}}}");
user_pref("gecko.buildID", "20150918100231");
user_pref("gecko.mstone", "41.0");
user_pref("idle.lastDailyNotification", 1456308745);
user_pref("media.gmp-gmpopenh264.lastUpdate", 1456307329);
user_pref("media.gmp-gmpopenh264.version", "1.5.3");
user_pref("media.gmp-manager.buildID", "20150918100231");
user_pref("media.gmp-manager.lastCheck", 1456307325);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1456308745);
user_pref("places.history.expiration.transient_current_max_pages", 12822);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateClearSavedPwdsOnExit", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1456308745);
user_pref("toolkit.startup.last_success", 1456325074);
user_pref("toolkit.telemetry.cachedClientID", "16b4cc14-8636-459c-b815-978fbfcb407e");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
